#server props https://minecraft.gamepedia.com/Server.properties#Bedrock_Edition_3

version: '3.4'

services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      GAMEMODE: adventure 
      DIFFICULTY: normal
      SERVER-NAME: minecraft-home
    ports:
      - 19132:19132/udp
    volumes:
      - bds:/data
    stdin_open: true
    tty: true

volumes:
  bds: {}